# Generated by Django 4.2.3 on 2023-07-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='page_id',
            field=models.IntegerField(default=1),
        ),
    ]
